{% set name = "webdav4" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/webdav4-{{ version }}.tar.gz
  sha256: 387da6f0ee384e77149dddd9bcfd434afa155882f6c440a529a7cb458624407f

build:
  number: 1
  noarch: python
  entry_points:
    - dav = webdav4.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.9.0
    - hatch-vcs
  run:
    - httpx >=0.20.0,<1.0.0
    - python >={{ python_min }}
    - python-dateutil >=2.8.1
    - fsspec >=2021.7.0

test:
  imports:
    - webdav4
  commands:
    - pip check
    - dav --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/skshetry/webdav4
  summary: WebDAV client library with an fsspec-based filesystem and a CLI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skshetry
    - efiop
