{% set name = "webdav4" %}
{% set version = "0.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/webdav4-{{ version }}.tar.gz
  sha256: 0d1e29f743def2c2ae2aab5e152757e1d8bfacfd7b7985764824308ebde1ff29

build:
  number: 0
  noarch: python
  entry_points:
    - dav = webdav4.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm >=6.3.1
  run:
    - httpx ==0.20.0
    - python >=3.6
    - python-dateutil >=2.8.1
    - fsspec >=2021.7.0

test:
  imports:
    - webdav4
  commands:
    - pip check
    - dav --help
  requires:
    - pip

about:
  home: https://github.com/skshetry/webdav4
  summary: WebDAV client library with an fsspec-based filesystem and a CLI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skshetry
    - efiop
