{% set name = "webdav4" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/webdav4-{{ version }}.tar.gz
  sha256: a9428ea5061fdabcdfff799891046400ece576fd57cf5b7cab75fa65a8e28ab5

build:
  number: 0
  noarch: python
  entry_points:
    - dav = webdav4.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
    - setuptools-scm ==6.0.1
  run:
    - httpx >=0.18.2
    - python >=3.6
    - python-dateutil >=2.8.1
    - fsspec ==2021.7.0

test:
  imports:
    - webdav4
  commands:
    - pip check
    - dav --help
  requires:
    - pip

about:
  home: https://github.com/skshetry/webdav4
  summary: WebDAV client library with an fsspec-based filesystem and a CLI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skshetry
    - efiop
